export const BreakTypes = {
  END_BREAK: "@break/END_BREAK",
  CLOSE_BREAK_SCREEN: "@break/CLOSE_BREAK_SCREEN",
  START_BREAK: "@break/START_BREAK",
  SET_WINDOW_CHANGED: "@break/SET_WINDOW_CHANGED",
  START_POPUP: "@break/START_POPUP",
  CANCEL_BREAK: "@break/CANCEL_BREAK",
  SET_BREAK_TRIGGERED: "@break/SET_BREAK_TRIGGERED",
};
