export const SET_NAME = "SET_NAME";
export const SET_BREAK_MESSAGE = "SET_BREAK_MESSAGE";
export const SET_SCHEDULED_BREAKS = "SET_SCHEDULED_BREAKS";
export const SET_SCREEN_TIME = "SET_SCREEN_TIME";
export const SET_REGULAR_BREAK_LENGTH = "SET_REGULAR_BREAK_LENGTH";
export const SET_REGULAR_BREAK_INTERVAL = "SET_REGULAR_BREAK_INTERVAL";
export const SET_OVERRIDE_SITES = "SET_OVERRIDE_SITES";
export const SET_ALL_OVERRIDES = "SET_ALL_OVERRIDES";
export const SET_ONBOARDING_COMPLETE = "SET_ONBOARDING_COMPLETE";
export const LOGIN_USER = "LOGIN_USER";
export const AW_CHECKED = "AW_CHECKED";
export const ADD_ONB_INFO = "ADD_ONB_INFO";

export const RESET = "RESET";
