export const PastTypes = {
  ADD_MINUTE: "@past/ADD_MINUTE",
  ADD_INTERVAL_BREAK: "@past/ADD_INTERVAL_BREAK",
  BACKUP_AW_DATA: "@past/BACKUP_AW_DATA",
  SAVE_BREAK_DATA: "@past/SAVE_BREAK_DATA",
  SAVE_INIT_BREAK_DATA: "@past/SAVE_INIT_BREAK_DATA",
  SET_TODAY: "@past/SET_TODAY",
  SET_AW_UP_NUM: "@past/SET_AW_UP_NUM",
  ADD_WEEKLY: "@past/ADD_WEEKLY",
  ADD_WEEKLY_EXTRA: "@past/ADD_WEEKLY_EXTRA",
  SET_WEEKLY_REM: "@past/SET_WEEKLY_REM",
  SET_TAKEN_ID: "@past/SET_TAKEN_ID",
  SET_TAKEN_ID_APP: "@past/SET_TAKEN_ID_APP",
};
